version: '3'
services:
  docker-streamlit: # サービス名に大文字は使用しない
    image: docker-streamlit # イメージ名の設定
    restart: always # exec 時に再起動する
    build: .
    container_name: 'docker-streamlit-container'
    ports: # ポートフォワーディング
      - "8001:8001" # （ローカルホストのポート）:（マウント先のポート）
    working_dir: '/root/'
    tty: true # docker-compose up したコンテナを起動させ続ける
    volumes: # ボリュームのマウント
      - ./src:/root/src/ #（ローカルホストのディレクトリ）:（マウント先のディレクトリ）